apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crud-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/muhresta/crud-app-cd.git
    targetRevision: HEAD
    path: ./crud-app
  destination:
    server: https://kubernetes.default.svc
    namespace: crud-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true