apiVersion: v1
kind: Service
metadata:
  name: crud-app-service
  spec:
    selector:
      app.kubernetes.io/name: crud-app
    ports:
      - name: crud-app-port
        protocol: TCP
        port: 80
        targetPort: 3000
    type: NodePort