apiVersion: v1
kind: Service
metadata:
  name: crud-app-service
spec:
  selector:
    app.kubernetes.io/name: crud-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
      NodePort: 32520
  type: NodePort